sudo: required

branches:
  only:
  - master

script:
  - make build

deploy:
  local-dir: .dist/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: blog.julianxhokaxhiu.com
  on:
    branch: master
