sudo: required

branches:
  only:
  - master

install:
  - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.57.1/hugo_0.57.1_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
- make build

deploy:
  local-dir: .dist/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: blog.julianxhokaxhiu.com
  on:
    branch: master
