# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: A Developer's Blog
subtitle:
description:
author: Julian Xhokaxhiu
language:
  - en
  - it
timezone: Europe/Berlin

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.julianxhokaxhiu.com
root: /
permalink: :lang/:title/
permalink_defaults:
  lang: en

# Directory
source_dir: src
public_dir: _dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :lang/:year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  single_language_index: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
all_minifier: true

## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:julianxhokaxhiu/blog.julianxhokaxhiu.com.git
  branch: gh-pages

# Feed
feed:
  type: atom
  path: atom.xml
  limit: false
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Aliases
alias:
  welcome/index.html: en/welcome/
  lets-make-google-chrome-live/index.html: en/lets-make-google-chrome-live/
  lets-make-google-chrome-live-part-2/index.html: en/lets-make-google-chrome-live-part-2/
  how-to-fix-baloon-height-with-images-in-google-maps-api-v2/index.html: en/how-to-fix-baloon-height-with-images-in-google-maps-api-v2/
  autocomplete-extended/index.html: en/autocomplete-extended/
  jquery-storyline/index.html: en/jquery-storyline/
  contentflow-shadowbox-plugin/index.html: en/contentflow-shadowbox-plugin/
  grooveshark-mediakeys-reloaded/index.html: en/grooveshark-mediakeys-reloaded/
  little-christmas-surprise-for-you-nwm/index.html: en/little-christmas-surprise-for-you-nwm/
  how-to-fix-npm-path-of-nwm/index.html: en/how-to-fix-npm-path-of-nwm/
  jondesigns-smoothgallery-shadowbox-plugin/index.html: en/jondesigns-smoothgallery-shadowbox-plugin/
  lets-write-our-first-hello-mongodb-with-nodejs/index.html: en/lets-write-our-first-hello-mongodb-with-nodejs/
  samsung-galaxy-s-ii-which-is-the-best-rom/index.html: en/samsung-galaxy-s-ii-which-is-the-best-rom/
  backforward-mouse-button-for-logitech-ls1-on-ubuntu-12-04/index.html: en/backforward-mouse-button-for-logitech-ls1-on-ubuntu-12-04/
  best-kernel-for-samsung-galaxy-s2/index.html: en/best-kernel-for-samsung-galaxy-s2/
  rapid-script-to-test-etag-and-last-modified-http-headers/index.html: en/rapid-script-to-test-etag-and-last-modified-http-headers/
  jquery-youtube-live-feed/index.html: en/jquery-youtube-live-feed/
  install-ajenti-over-wd-mybook-world-edition-ii-with-debian/index.html: en/install-ajenti-over-wd-mybook-world-edition-ii-with-debian/
  fix-ntfs-3g-boot-message-warning-on-os-x-lionmountain-lion/index.html: en/fix-ntfs-3g-boot-message-warning-on-os-x-lionmountain-lion/
  contacteditor-ane-patch-for-ios6-xcode-4-5-and-adobe-air-3-5-sdk/index.html: en/contacteditor-ane-patch-for-ios6-xcode-4-5-and-adobe-air-3-5-sdk/
  jquery-itunes-store-search/index.html: en/jquery-itunes-store-search/
  expand-your-storage-on-cyanogenmod-with-simple2ext/index.html: en/expand-your-storage-on-cyanogenmod-with-simple2ext/
  center-the-new-youtube-layout-with-yt-native-center-layout/index.html: en/center-the-new-youtube-layout-with-yt-native-center-layout/
  how-to-run-whatsapp-on-your-pcmac-using-bluestacks/index.html: en/how-to-run-whatsapp-on-your-pcmac-using-bluestacks/
  best-setup-for-samsung-galaxy-s2/index.html: en/best-setup-for-samsung-galaxy-s2/
  projecttreetemplater-a-new-sublime-text-2-plugin-to-manage-your/index.html: en/projecttreetemplater-a-new-sublime-text-2-plugin-to-manage-your/
  pushing-wordpress-performance-to-the-limits/index.html: en/pushing-wordpress-performance-to-the-limits/
  when-wordpress-meets-twig/index.html: en/when-wordpress-meets-twig/
  twigpress-a-boilerplate-twig-engine-theme-for-wordpress/index.html: en/twigpress-a-boilerplate-twig-engine-theme-for-wordpress/
  expand-your-storage-on-cyanogenmod-with-mounts2sd/index.html: en/expand-your-storage-on-cyanogenmod-with-mounts2sd/
  daapjs-daap-resolver-for-tomahawk-player/index.html: en/daapjs-daap-resolver-for-tomahawk-player/
  how-to-setup-an-ssh-server-on-zyxel-nsa320/index.html: en/how-to-setup-an-ssh-server-on-zyxel-nsa320/
  install-debian-wheezy-zyxel-nsa320/index.html: en/install-debian-wheezy-zyxel-nsa320/
  how-to-install-bolt-cms-on-namecheap-shared-hosting/index.html: en/how-to-install-bolt-cms-on-namecheap-shared-hosting/
  how-to-install-supersu-on-hamlet-zelig-pad-210g/index.html: en/how-to-install-supersu-on-hamlet-zelig-pad-210g/
  extract-your-spotify-playlist-from-google-chrome/index.html: en/extract-your-spotify-playlist-from-google-chrome/
  how-the-cm-ota-server-works-and-how-to-implement-and-use-ours/index.html: en/how-the-cm-ota-server-works-and-how-to-implement-and-use-ours/
  grooveshark-and-deezer-mediakeys-extensions-got-a-bigger-update/index.html: en/grooveshark-and-deezer-mediakeys-extensions-got-a-bigger-update/
  frontend-development-on-steroids-from-localhost-to-environment-without-a-deploy/index.html: en/frontend-development-on-steroids-from-localhost-to-environment-without-a-deploy/
